
POST https://1qw45krk94.execute-api.eu-west-1.amazonaws.com/prod/personas
Content-Type: application/json

{
  "first_name" : "Giona",
  "last_name" :  "Test",
  "phone_number" : "12321321",
  "address" :  "adsadasda"
}

### GET By ID
GET https://1qw45krk94.execute-api.eu-west-1.amazonaws.com/prod/personas/5a8da3a3-8f1c-4675-a035-400f7d203033
Content-Type: application/json

### GET ALL
GET https://1qw45krk94.execute-api.eu-west-1.amazonaws.com/prod/personas
Content-Type: application/json

### Localhost


POST http://127.0.0.1:3000/personas
Content-Type: application/json

{
  "first_name" : "Giona",
  "last_name" :  "Test",
  "phone_number" : "12321321",
  "address" :  "adsadasda"
}