
# PROD
### POST CREATE new PERSONAS
POST https://1qw45krk94.execute-api.eu-west-1.amazonaws.com/prod/personas
Content-Type: application/json

{
  "id" : "3",
  "first_name" : "Giona",
  "last_name" :  "TestRRR",
  "phone_number" : "12321321",
  "address" :  "adsadasda"
}

### GET By ID
GET https://1qw45krk94.execute-api.eu-west-1.amazonaws.com/prod/personas/3
Content-Type: application/json

### GET ALL
GET https://1qw45krk94.execute-api.eu-west-1.amazonaws.com/prod/personas
Content-Type: application/json

# Localhost

### POST CREATE new PERSONAS in LOCALHOST
POST http://127.0.0.1:3000/personas
Content-Type: application/json

{
  "first_name" : "Giona",
  "last_name" :  "Test",
  "phone_number" : "12321321",
  "address" :  "adsadasda"
}


### DEV
POST https://ugws6zbab4.execute-api.eu-west-1.amazonaws.com/prod/dev/personas